version: '3.8'
services:

  # PHP-FPM - Service
  broadcasting:
    build:
      args:
        user: www
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: broadcasting-image
    container_name: broadcasting
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www/
      - ./docker-files/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "6001:6001"
    networks:
      - app-network

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker-files/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  db:
    image: mysql:5.7.22
    container_name: broadcasting-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
#      - ./storage/dbdata:/var/lib/mysql
      - datadb:/var/lib/mysql
      - ./docker-files/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - 33069:3306
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  datadb:
    driver: local
